// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEf6pL9vmdyPwKQ68FdFYkFhcU7cyctkc',
    appId: '1:722373402894:web:357472afda8471fc5ab75f',
    messagingSenderId: '722373402894',
    projectId: 'zipkart-firebase',
    authDomain: 'zipkart-firebase.firebaseapp.com',
    storageBucket: 'zipkart-firebase.firebasestorage.app',
    measurementId: 'G-63V76B138V',
    databaseURL: 'https://zipkart-firebase.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7VluTKEpDmgpwqmseVlh4vOfKYXCIv1I',
    appId: '1:722373402894:android:660c450c9d634b435ab75f',
    messagingSenderId: '722373402894',
    projectId: 'zipkart-firebase',
    storageBucket: 'zipkart-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpRktdnaaA04sbVm-9M3Tp91kJZ7MhbCQ',
    appId: '1:722373402894:ios:9e438eae95a285e85ab75f',
    messagingSenderId: '722373402894',
    projectId: 'zipkart-firebase',
    storageBucket: 'zipkart-firebase.firebasestorage.app',
    iosBundleId: 'com.example.zipkartFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpRktdnaaA04sbVm-9M3Tp91kJZ7MhbCQ',
    appId: '1:722373402894:ios:9e438eae95a285e85ab75f',
    messagingSenderId: '722373402894',
    projectId: 'zipkart-firebase',
    storageBucket: 'zipkart-firebase.firebasestorage.app',
    iosBundleId: 'com.example.zipkartFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEf6pL9vmdyPwKQ68FdFYkFhcU7cyctkc',
    appId: '1:722373402894:web:4f516cad24a750255ab75f',
    messagingSenderId: '722373402894',
    projectId: 'zipkart-firebase',
    authDomain: 'zipkart-firebase.firebaseapp.com',
    storageBucket: 'zipkart-firebase.firebasestorage.app',
    measurementId: 'G-Y7SBJJ73BH',
  );

}